pidev2/src/Entity/Guide.php
<?php

namespace App\Entity;

use App\Repository\GuideRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=GuideRepository::class)
 */
class Guide
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Email is required")
     * @Assert\Email(message = "The email '{{ value }}' is not a valid
    email.")
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     * * @Assert\Length(
     *   min="8",
     *   max="8"
     * )
     */
    private $num_tel;

    /**
     * @ORM\ManyToOne(targetEntity=Voyage::class, inversedBy="guide")
     */
    private $voyage;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getVoyage(): ?Voyage
    {
        return $this->voyage;
    }

    public function setVoyage(?Voyage $voyage): self
    {
        $this->voyage = $voyage;

        return $this;
    }
}

pidev2/templates/front/panier.html.twig
{% extends 'front.html.twig' %}

{% block title %}Voyages{% endblock %}

{% block body %}

<center>
        <h1> Votre Panier </h1>

        {% if items | length > 0 %}
            <table class="table" border="1">
            <thead>
            <tr>
                <th><h6>Destination</h6></th>
                <th><h6>Prix</h6></th>
                <th><h6>Periode</h6></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.voyage.Destination }}</td>
                    <td>{{ item.voyage.Prix }}</td>
                    <td>{{ item.voyage.Periode }}</td>
                    <td>
                        <a href="{{ path('removePanier',{'id':item.voyage.id }) }}">
                            <button class="btn btn-danger btn-sm fas fa-trash">
                                Supprimer
                            </button>

                        </a>
                    </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

        {% else %}
            <p>Le panier est vide</p>
        {% endif %}
</center>


{% endblock %}

pidev2/templates/front/readG.html.twig
{% extends 'front.html.twig' %}

{% block title %}Guides disponibles{% endblock %}

{% block body %}
    <center>
<br><br>
        <h1>Guides disponibles</h1>
        <a href="{{ path('listDQLG') }}"><button> Trier </button> </a> <br> <br>

        <table class="table" border="1" >

            <tbody>
            <tr>
            {% for guide in guides %}

                    <td>

                 <h6><label>Nom :</label>{{ guide.nom }}</h6>
                 <h6><label>Prenom :</label>{{ guide.prenom }}</h6>
                 <h6><label>Email :</label>{{ guide.email }}</h6>
                 <h6><label>Num_tel :</label>{{ guide.numTel }}</h6>
                 <h6><label>Voyage :</label>{{ guide.voyage.Destination}}</h6>
             </td>

            {% endfor %}
                </tr>

            </tbody>
        </table>



    </center>
{% endblock %}

pidev2/templates/front/readV.html.twig
{% extends 'front.html.twig' %}

{% block title %}Voyages{% endblock %}

{% block body %}
    <div class="navigation">
        {{ knp_pagination_render(voyages) }}
    </div>
        <center>

        <h1>Voyages</h1>

        <table class="table">
            <tbody>
            <tr>
            {% for voyage in voyages %}

                <td>
                    <img src="{{ vich_uploader_asset(voyage) }}" alt="{{ voyage.Destination}}" height="350" width="300"/><br></li>
                    <h6>Destination : <span>{{ voyage.Destination }}</span> </h6>
                    <h6>Prix :{{ voyage.Prix }}</h6>
                    <h6>Période :{{ voyage.Periode }}</h6>

                    <a href="{{ path('addPanier',{'id':voyage.id }) }}">
                    <button class="btn btn-success float-right fas fa-shopping-cart" > Réserver</button>
                    </a>
                </td>

            {% endfor %}
            </tr>
            </tbody>
        </table>
<br>
            <html>
            <head>
                {% for voyage in voyages %}
                <script src="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"></script>
                <link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css"/>

                <script type="text/javascript">
                    window.onload = function() {
                        L.mapquest.key = 'GtMAuVAD2yGyDJ9gKa56B0qvGfaKiTaX';

                        var map = L.mapquest.map('map', {
                            center: [0, 0],
                            layers: L.mapquest.tileLayer('map'),
                            zoom: 14
                        });

                        L.mapquest.geocoding().geocode('{{ voyage.Destination }}');
                    }
                </script>
                {% endfor %}
            </head>

            <body style="border: 0; margin: 0;">
            <div id="map" style="width: 100%; height: 530px;"></div>

            </body>
            </html>

    </center>



{% endblock %}